currency_base = [
    ('Albania', 'Leke', 'ALL', 'Lek'),
    ('America', 'Dollars', 'USD', '$'),
    ('Afghanistan', 'Afghanis', 'AFN', '؋'),
    ('Argentina', 'Pesos', 'ARS', '$'),
    ('Aruba', 'Guilders', 'AWG', 'ƒ'),
    ('Australia', 'Dollars', 'AUD', '$'),
    ('Azerbaijan', 'New Manats', 'AZN', 'ман'),
    ('Bahamas', 'Dollars', 'BSD', '$'),
    ('Barbados', 'Dollars', 'BBD', '$'),
    ('Belarus', 'Rubles', 'BYR', 'p.'),
    ('Belgium', 'Euro', 'EUR', '€'),
    ('Beliz', 'Dollars', 'BZD', 'BZ$'),
    ('Bermuda', 'Dollars', 'BMD', '$'),
    ('Bolivia', 'Bolivianos', 'BOB', '$b'),
    ('Bosnia and Herzegovina', 'Convertible Marka', 'BAM', 'KM'),
    ('Botswana', 'Pula''s', 'BWP', 'P'),
    ('Bulgaria', 'Leva', 'BGN', 'лв'),
    ('Brazil', 'Reais', 'BRL', 'R$'),
    ('Britain (United Kingdom)', 'Pounds', 'GBP', '£'),
    ('Brunei Darussalam', 'Dollars', 'BND', '$'),
    ('Cambodia', 'Riels', 'KHR', '៛'),
    ('Canada', 'Dollars', 'CAD', '$'),
    ('Cayman Islands', 'Dollars', 'KYD', '$'),
    ('Chile', 'Pesos', 'CLP', '$'),
    ('China', 'Yuan Renminbi', 'CNY', '¥'),
    ('Colombia', 'Pesos', 'COP', '$'),
    ('Costa Rica', 'Colón', 'CRC', '₡'),
    ('Croatia', 'Kuna', 'HRK', 'kn'),
    ('Cuba', 'Pesos', 'CUP', '₱'),
    ('Cyprus', 'Euro', 'EUR', '€'),
    ('Czech Republic', 'Koruny', 'CZK', 'Kč'),
    ('Denmark', 'Kroner', 'DKK', 'kr'),
    ('Dominican Republic', 'Pesos', 'DOP', 'RD$'),
    ('East Caribbean', 'Dollars', 'XCD', '$'),
    ('Egypt', 'Pounds', 'EGP', '£'),
    ('El Salvador', 'Colones', 'SVC', '$'),
    ('England (United Kingdom)', 'Pounds', 'GBP', '£'),
    ('Euro', 'Euro', 'EUR', '€'),
    ('Falkland Islands', 'Pounds', 'FKP', '£'),
    ('Fiji', 'Dollars', 'FJD', '$'),
    ('France', 'Euro', 'EUR', '€'),
    ('Ghana', 'Cedis', 'GHC', '¢'),
    ('Gibraltar', 'Pounds', 'GIP', '£'),
    ('Greece', 'Euro', 'EUR', '€'),
    ('Guatemala', 'Quetzales', 'GTQ', 'Q'),
    ('Guernsey', 'Pounds', 'GGP', '£'),
    ('Guyana', 'Dollars', 'GYD', '$'),
    ('Holland (Netherlands)', 'Euro', 'EUR', '€'),
    ('Honduras', 'Lempiras', 'HNL', 'L'),
    ('Hong Kong', 'Dollars', 'HKD', 'HK$'),
    ('Hungary', 'Forint', 'HUF', 'Ft'),
    ('Iceland', 'Kronur', 'ISK', 'kr'),
    ('India', 'Rupees', 'INR', u"\u20B9"),
    ('Indonesia', 'Rupiahs', 'IDR', 'Rp'),
    ('Iran', 'Rials', 'IRR', '﷼'),
    ('Ireland', 'Euro', 'EUR', '€'),
    ('Isle of Man', 'Pounds', 'IMP', '£'),
    ('Israel', 'New Shekels', 'ILS', '₪'),
    ('Italy', 'Euro', 'EUR', '€'),
    ('Jamaica', 'Dollars', 'JMD', 'J$'),
    ('Japan', 'Yen', 'JPY', '¥'),
    ('Jersey', 'Pounds', 'JEP', '£'),
    ('Kazakhstan', 'Tenge', 'KZT', 'лв'),
    ('Korea (North)', 'Won', 'KPW', '₩'),
    ('Korea (South)', 'Won', 'KRW', '₩'),
    ('Kyrgyzstan', 'Soms', 'KGS', 'лв'),
    ('Laos', 'Kips', 'LAK', '₭'),
    ('Latvia', 'Lati', 'LVL', 'Ls'),
    ('Lebanon', 'Pounds', 'LBP', '£'),
    ('Liberia', 'Dollars', 'LRD', '$'),
    ('Liechtenstein', 'Switzerland Francs', 'CHF', 'fr.'),
    ('Lithuania', 'Litai', 'LTL', 'Lt'),
    ('Luxembourg', 'Euro', 'EUR', '€'),
    ('Macedonia', 'Denars', 'MKD', 'ден'),
    ('Malaysia', 'Ringgits', 'MYR', 'RM'),
    ('Malta', 'Euro', 'EUR', '€'),
    ('Mauritius', 'Rupees', 'MUR', '₨'),
    ('Mexico', 'Pesos', 'MXN', '$'),
    ('Mongolia', 'Tugriks', 'MNT', '₮'),
    ('Mozambique', 'Meticais', 'MZN', 'MT'),
    ('Namibia', 'Dollars', 'NAD', '$'),
    ('Nepal', 'Rupees', 'NPR', '₨'),
    ('Netherlands Antilles', 'Guilders', 'ANG', 'ƒ'),
    ('Netherlands', 'Euro', 'EUR', '€'),
    ('New Zealand', 'Dollars', 'NZD', '$'),
    ('Nicaragua', 'Cordobas', 'NIO', 'C$'),
    ('Nigeria', 'Nairas', 'NGN', '₦'),
    ('North Korea', 'Won', 'KPW', '₩'),
    ('Norway', 'Krone', 'NOK', 'kr'),
    ('Oman', 'Rials', 'OMR', '﷼'),
    ('Pakistan', 'Rupees', 'PKR', '₨'),
    ('Panama', 'Balboa', 'PAB', 'B/.'),
    ('Paraguay', 'Guarani', 'PYG', 'Gs'),
    ('Peru', 'Nuevos Soles', 'PEN', 'S/.'),
    ('Philippines', 'Pesos', 'PHP', '₱'),
    ('Poland', 'Zlotych', 'PLN', 'zł'),
    ('Qatar', 'Rials', 'QAR', '﷼'),
    ('Romania', 'New Lei', 'RON', 'lei'),
    ('Russia', 'Rubles', 'RUB', 'руб'),
    ('Saint Helena', 'Pounds', 'SHP', '£'),
    ('Saudi Arabia', 'Riyals', 'SAR', '﷼'),
    ('Serbia', 'Dinars', 'RSD', 'Дин.'),
    ('Seychelles', 'Rupees', 'SCR', '₨'),
    ('Singapore', 'Dollars', 'SGD', '$'),
    ('Slovenia', 'Euro', 'EUR', '€'),
    ('Solomon Islands', 'Dollars', 'SBD', '$'),
    ('Somalia', 'Shillings', 'SOS', 'S'),
    ('South Africa', 'Rand', 'ZAR', 'R'),
    ('South Korea', 'Won', 'KRW', '₩'),
    ('Spain', 'Euro', 'EUR', '€'),
    ('Sri Lanka', 'Rupees', 'LKR', '₨'),
    ('Sweden', 'Kronor', 'SEK', 'kr'),
    ('Switzerland', 'Francs', 'CHF', 'fr.'),
    ('Suriname', 'Dollars', 'SRD', '$'),
    ('Syria', 'Pounds', 'SYP', '£'),
    ('Taiwan', 'New Dollars', 'TWD', '元'),
    ('Thailand', 'Baht', 'THB', '฿'),
    ('Trinidad and Tobago', 'Dollars', 'TTD', 'TT$'),
    ('Turkey', 'Lira', 'TRY', '₺'),
    ('Turkey', 'Liras', 'TRL', '£'),
    ('Tuvalu', 'Dollars', 'TVD', '$'),
    ('Ukraine', 'Hryvnia', 'UAH', '₴'),
    ('United Kingdom', 'Pounds', 'GBP', '£'),
    ('United States of America', 'Dollars', 'USD', '$'),
    ('Uruguay', 'Pesos', 'UYU', '$U'),
    ('Uzbekistan', 'Sums', 'UZS', 'лв'),
    ('Vatican City', 'Euro', 'EUR', '€'),
    ('Venezuela', 'Bolivares Fuertes', 'VEF', 'Bs'),
    ('Vietnam', 'Dong', 'VND', '₫'),
    ('Yemen', 'Rials', 'YER', '﷼'),
    ('Zimbabwe', 'Zimbabwe Dollars', 'ZWD', 'Z$')
]

currency_list = [
    ('ALL', 'Albania - Leke - ALL - Lek'),
    ('USD', 'America - Dollars - USD - $'),
    ('AFN', 'Afghanistan - Afghanis - AFN - ؋'),
    ('ARS', 'Argentina - Pesos - ARS - $'),
    ('AWG', 'Aruba - Guilders - AWG - ƒ'),
    ('AUD', 'Australia - Dollars - AUD - $'),
    ('AZN', 'Azerbaijan - New Manats - AZN - ман'),
    ('BSD', 'Bahamas - Dollars - BSD - $'),
    ('BBD', 'Barbados - Dollars - BBD - $'),
    ('BYR', 'Belarus - Rubles - BYR - p.'),
    ('EUR', 'Belgium - Euro - EUR - €'),
    ('BZD', 'Beliz - Dollars - BZD - BZ$'),
    ('BMD', 'Bermuda - Dollars - BMD - $'),
    ('BOB', 'Bolivia - Bolivianos - BOB - $b'),
    ('BAM', 'Bosnia and Herzegovina - Convertible Marka - BAM - KM'),
    ('BWP', 'Botswana - Pulas - BWP - P'),
    ('BGN', 'Bulgaria - Leva - BGN - лв'),
    ('BRL', 'Brazil - Reais - BRL - R$'),
    ('GBP', 'Britain (United Kingdom) - Pounds - GBP - £'),
    ('BND', 'Brunei Darussalam - Dollars - BND - $'),
    ('KHR', 'Cambodia - Riels - KHR - ៛'),
    ('CAD', 'Canada - Dollars - CAD - $'),
    ('KYD', 'Cayman Islands - Dollars - KYD - $'),
    ('CLP', 'Chile - Pesos - CLP - $'),
    ('CNY', 'China - Yuan Renminbi - CNY - ¥'),
    ('COP', 'Colombia - Pesos - COP - $'),
    ('CRC', 'Costa Rica - Colón - CRC - ₡'),
    ('HRK', 'Croatia - Kuna - HRK - kn'),
    ('CUP', 'Cuba - Pesos - CUP - ₱'),
    ('EUR', 'Cyprus - Euro - EUR - €'),
    ('CZK', 'Czech Republic - Koruny - CZK - Kč'),
    ('DKK', 'Denmark - Kroner - DKK - kr'),
    ('DOP', 'Dominican Republic - Pesos - DOP  - RD$'),
    ('XCD', 'East Caribbean - Dollars - XCD - $'),
    ('EGP', 'Egypt - Pounds - EGP - £'),
    ('SVC', 'El Salvador - Colones - SVC - $'),
    ('GBP', 'England (United Kingdom) - Pounds - GBP - £'),
    ('EUR', 'Euro - Euro - EUR - €'),
    ('FKP', 'Falkland Islands - Pounds - FKP - £'),
    ('FJD', 'Fiji - Dollars - FJD - $'),
    ('EUR', 'France - Euro - EUR - €'),
    ('GHC', 'Ghana - Cedis - GHC - ¢'),
    ('GIP', 'Gibraltar - Pounds - GIP - £'),
    ('EUR', 'Greece - Euro - EUR - €'),
    ('GTQ', 'Guatemala - Quetzales - GTQ - Q'),
    ('GGP', 'Guernsey - Pounds - GGP - £'),
    ('GYD', 'Guyana - Dollars - GYD - $'),
    ('EUR', 'Holland (Netherlands) - Euro - EUR - €'),
    ('HNL', 'Honduras - Lempiras - HNL - L'),
    ('HKD', 'Hong Kong - Dollars - HKD - HK$'),
    ('HUF', 'Hungary - Forint - HUF - Ft'),
    ('ISK', 'Iceland - Kronur - ISK - kr'),
    ('INR', 'India - Rupees - INR - ₹'),
    ('IDR', 'Indonesia - Rupiahs - IDR - Rp'),
    ('IRR', 'Iran - Rials - IRR - ﷼'),
    ('EUR', 'Ireland - Euro - EUR - €'),
    ('IMP', 'Isle of Man - Pounds - IMP - £'),
    ('ILS', 'Israel - New Shekels - ILS - ₪'),
    ('EUR', 'Italy - Euro - EUR - €'),
    ('JMD', 'Jamaica - Dollars - JMD - J$'),
    ('JPY', 'Japan - Yen - JPY - ¥'),
    ('JEP', 'Jersey - Pounds - JEP - £'),
    ('KZT', 'Kazakhstan - Tenge - KZT - лв'),
    ('KPW', 'Korea (North) - Won - KPW - ₩'),
    ('KRW', 'Korea (South) - Won - KRW - ₩'),
    ('KGS', 'Kyrgyzstan - Soms - KGS - лв'),
    ('LAK', 'Laos - Kips - LAK - ₭'),
    ('LVL', 'Latvia - Lati - LVL - Ls'),
    ('LBP', 'Lebanon - Pounds - LBP - £'),
    ('LRD', 'Liberia - Dollars - LRD - $'),
    ('CHF', 'Liechtenstein - Switzerland Francs - CHF - fr.'),
    ('LTL', 'Lithuania - Litai - LTL - Lt'),
    ('EUR', 'Luxembourg - Euro - EUR - €'),
    ('MKD', 'Macedonia - Denars - MKD - ден'),
    ('MYR', 'Malaysia - Ringgits - MYR - RM'),
    ('EUR', 'Malta - Euro - EUR - €'),
    ('MUR', 'Mauritius - Rupees - MUR - ₨'),
    ('MXN', 'Mexico - Pesos - MXN - $'),
    ('MNT', 'Mongolia - Tugriks - MNT - ₮'),
    ('MZN', 'Mozambique - Meticais - MZN - MT'),
    ('NAD', 'Namibia - Dollars - NAD - $'),
    ('NPR', 'Nepal - Rupees - NPR - ₨'),
    ('ANG', 'Netherlands Antilles - Guilders - ANG - ƒ'),
    ('EUR', 'Netherlands - Euro - EUR - €'),
    ('NZD', 'New Zealand - Dollars - NZD - $'),
    ('NIO', 'Nicaragua - Cordobas - NIO - C$'),
    ('NGN', 'Nigeria - Nairas - NGN - ₦'),
    ('KPW', 'North Korea - Won - KPW - ₩'),
    ('NOK', 'Norway - Krone - NOK - kr'),
    ('OMR', 'Oman - Rials - OMR - ﷼'),
    ('PKR', 'Pakistan - Rupees - PKR - ₨'),
    ('PAB', 'Panama - Balboa - PAB - B/.'),
    ('PYG', 'Paraguay - Guarani - PYG - Gs'),
    ('PEN', 'Peru - Nuevos Soles - PEN - S/.'),
    ('PHP', 'Philippines - Pesos - PHP - ₱'),
    ('PLN', 'Poland - Zlotych - PLN - zł'),
    ('QAR', 'Qatar - Rials - QAR - ﷼'),
    ('RON', 'Romania - New Lei - RON - lei'),
    ('RUB', 'Russia - Rubles - RUB - руб'),
    ('SHP', 'Saint Helena - Pounds - SHP - £'),
    ('SAR', 'Saudi Arabia - Riyals - SAR - ﷼'),
    ('RSD', 'Serbia - Dinars - RSD - Дин.'),
    ('SCR', 'Seychelles - Rupees - SCR - ₨'),
    ('SGD', 'Singapore - Dollars - SGD - $'),
    ('EUR', 'Slovenia - Euro - EUR - €'),
    ('SBD', 'Solomon Islands - Dollars - SBD - $'),
    ('SOS', 'Somalia - Shillings - SOS - S'),
    ('ZAR', 'South Africa - Rand - ZAR - R'),
    ('KRW', 'South Korea - Won - KRW - ₩'),
    ('EUR', 'Spain - Euro - EUR - €'),
    ('LKR', 'Sri Lanka - Rupees - LKR - ₨'),
    ('SEK', 'Sweden - Kronor - SEK - kr'),
    ('CHF', 'Switzerland - Francs - CHF - fr.'),
    ('SRD', 'Suriname - Dollars - SRD - $'),
    ('SYP', 'Syria - Pounds - SYP - £'),
    ('TWD', 'Taiwan - New Dollars - TWD - 元'),
    ('THB', 'Thailand - Baht - THB - ฿'),
    ('TTD', 'Trinidad and Tobago - Dollars - TTD - TT$'),
    ('TRY', 'Turkey - Lira - TRY - ₺'),
    ('TRL', 'Turkey - Liras - TRL - £'),
    ('TVD', 'Tuvalu - Dollars - TVD - $'),
    ('UAH', 'Ukraine - Hryvnia - UAH - ₴'),
    ('GBP', 'United Kingdom - Pounds - GBP - £'),
    ('USD', 'United States of America - Dollars - USD - $'),
    ('UYU', 'Uruguay - Pesos - UYU - $U'),
    ('UZS', 'Uzbekistan - Sums - UZS - лв'),
    ('EUR', 'Vatican City - Euro - EUR - €'),
    ('VEF', 'Venezuela - Bolivares Fuertes - VEF - Bs'),
    ('VND', 'Vietnam - Dong - VND - ₫'),
    ('YER', 'Yemen - Rials - YER - ﷼'),
    ('ZWD', 'Zimbabwe - Zimbabwe Dollars - ZWD - Z$'),
]
currency_sym = {
    'ALL': 'Lek',
    'USD': '$',
    'AFN': '؋',
    'ARS': '$',
    'AWG': 'ƒ',
    'AUD': '$',
    'AZN': 'ман',
    'BSD': '$',
    'BBD': '$',
    'BYR': 'p.',
    'EUR': '€',
    'BZD': 'BZ$',
    'BMD': '$',
    'BOB': '$b',
    'BAM': 'KM',
    'BWP': 'P',
    'BGN': 'лв',
    'BRL': 'R$',
    'GBP': '£',
    'BND': '$',
    'KHR': '៛',
    'CAD': '$',
    'KYD': '$',
    'CLP': '$',
    'CNY': '¥',
    'COP': '$',
    'CRC': '₡',
    'HRK': 'kn',
    'CUP': '₱',
    'CZK': 'Kč',
    'DKK': 'kr',
    'DOP': 'RD$',
    'XCD': '$',
    'EGP': '£',
    'SVC': '$',
    'FKP': '£',
    'FJD': '$',
    'GHC': '¢',
    'GIP': '£',
    'GTQ': 'Q',
    'GGP': '£',
    'GYD': '$',
    'HNL': 'L',
    'HKD': 'HK$',
    'HUF': 'Ft',
    'ISK': 'kr',
    'INR': '₹',
    'IDR': 'Rp',
    'IRR': '﷼',
    'IMP': '£',
    'ILS': '₪',
    'JMD': 'J$',
    'JPY': '¥',
    'JEP': '£',
    'KZT': 'лв',
    'KPW': '₩',
    'KRW': '₩',
    'KGS': 'лв',
    'LAK': '₭',
    'LVL': 'Ls',
    'LBP': '£',
    'LRD': '$',
    'CHF': 'fr.',
    'LTL': 'Lt',
    'MKD': 'ден',
    'MYR': 'RM',
    'MUR': '₨',
    'MXN': '$',
    'MNT': '₮',
    'MZN': 'MT',
    'NAD': '$',
    'NPR': '₨',
    'ANG': 'ƒ',
    'NZD': '$',
    'NIO': 'C$',
    'NGN': '₦',
    'NOK': 'kr',
    'OMR': '﷼',
    'PKR': '₨',
    'PAB': 'B/.',
    'PYG': 'Gs',
    'PEN': 'S/.',
    'PHP': '₱',
    'PLN': 'zł',
    'QAR': '﷼',
    'RON': 'lei',
    'RUB': 'руб',
    'SHP': '£',
    'SAR': '﷼',
    'RSD': 'Дин.',
    'SCR': '₨',
    'SGD': '$',
    'SBD': '$',
    'SOS': 'S',
    'ZAR': 'R',
    'LKR': '₨',
    'SEK': 'kr',
    'SRD': '$',
    'SYP': '£',
    'TWD': '元',
    'THB': '฿',
    'TTD': 'TT$',
    'TRY': '₺',
    'TRL': '£',
    'TVD': '$',
    'UAH': '₴',
    'UYU': '$U',
    'UZS': 'лв',
    'VEF': 'Bs',
    'VND': '₫',
    'YER': '﷼',
    'ZWD': 'Z$'
}
currency_dir = {
    'ALL': 'right',
    'USD': 'left',
    'AFN': 'left',
    'ARS': 'left',
    'AWG': 'left',
    'AUD': 'left',
    'AZN': 'right',
    'BSD': 'left',
    'BBD': 'left',
    'BYR': 'right',
    'EUR': 'left',
    'BZD': 'left',
    'BMD': 'left',
    'BOB': 'left',
    'BAM': 'right',
    'BWP': 'right',
    'BGN': 'right',
    'BRL': 'left',
    'GBP': 'left',
    'BND': 'left',
    'KHR': 'right',
    'CAD': 'left',
    'KYD': 'left',
    'CLP': 'left',
    'CNY': 'left',
    'COP': 'left',
    'CRC': 'right',
    'HRK': 'right',
    'CUP': 'left',
    'CZK': 'right',
    'DKK': 'left',
    'DOP': 'left',
    'XCD': 'left',
    'EGP': 'left',
    'SVC': 'left',
    'FKP': 'left',
    'FJD': 'left',
    'GHC': 'right',
    'GIP': 'left',
    'GTQ': 'right',
    'GGP': 'left',
    'GYD': 'left',
    'HNL': 'right',
    'HKD': 'left',
    'HUF': 'right',
    'ISK': 'right',
    'INR': 'left',
    'IDR': 'right',
    'IRR': 'right',
    'IMP': 'left',
    'ILS': 'left',
    'JMD': 'left',
    'JPY': 'left',
    'JEP': 'left',
    'KZT': 'right',
    'KPW': 'left',
    'KRW': 'left',
    'KGS': 'right',
    'LAK': 'right',
    'LVL': 'right',
    'LBP': 'left',
    'LRD': 'left',
    'CHF': 'left',
    'LTL': 'right',
    'MKD': 'right',
    'MYR': 'left',
    'MUR': 'right',
    'MXN': 'left',
    'MNT': 'right',
    'MZN': 'right',
    'NAD': 'left',
    'NPR': 'right',
    'ANG': 'right',
    'NZD': 'left',
    'NIO': 'left',
    'NGN': 'right',
    'NOK': 'left',
    'OMR': 'right',
    'PKR': 'right',
    'PAB': 'right',
    'PYG': 'right',
    'PEN': 'right',
    'PHP': 'left',
    'PLN': 'right',
    'QAR': 'right',
    'RON': 'right',
    'RUB': 'right',
    'SHP': 'left',
    'SAR': 'right',
    'RSD': 'right',
    'SCR': 'right',
    'SGD': 'left',
    'SBD': 'left',
    'SOS': 'right',
    'ZAR': 'left',
    'LKR': 'right',
    'SEK': 'right',
    'SRD': 'left',
    'SYP': 'left',
    'TWD': 'left',
    'THB': 'right',
    'TTD': 'left',
    'TRY': 'right',
    'TRL': 'left',
    'TVD': 'left',
    'UAH': 'right',
    'UYU': 'left',
    'UZS': 'right',
    'VEF': 'right',
    'VND': 'right',
    'YER': 'right',
    'ZWD': 'left'
}
# for c in currency_base:
#     print("('{0}', '{1} - {2} - {3} - {4}'),".format(c[2], c[0], c[1], c[2], c[3]))

# for c in currency_base:
#     print("('{0}', '{1}'),".format(c[2], c[3]))

# for c in currency_base:
#     print("('{0}', '{1}'),".format(c[2], c[3]))
