from django.urls import path, include
from . import views, forms
from django.contrib.auth import views as auth_views

urlpatterns = [
    # path('', auth_views.LoginView.as_view(form_class=forms.UserLoginForm), name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),

    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.SignUp.as_view(), name='signup'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html",
                                                                 form_class=forms.EmailValidationOnForgotPassword),
         name='password_reset'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),
         name='password_reset_done'),

    path('reset/<str:uidb64>/<str:token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html",
                                                     form_class=forms.SetPasswordForm),
         name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('settings/password_change/', views.change_password, name='settings_password_change'),

    path('activate/<str:uidb64>/<str:token>/', views.activate, name='activate'),
    path('role/new/', views.create_n_edit_role, name='createrole'),
    path('role/<int:role_id>/edit/', views.create_n_edit_role, name='editrole'),
    path('role/<int:role_id>/get/', views.get_permissions_for_role, name='get_permissions_for_role'),
    path('role/<int:role_id>/delete/', views.delete_role, name='deleterole'),
    path('roles/permission/update/', views.update_role, name='role_permissions_update'),
    path('roles/', views.view_role_permissions, name='viewroles'),
    path('employees/', views.view_company_employees, name='view_employees'),
    path('employee/new/', views.create_company_employee, name='new_employee'),
    path('employee/verify_on_boarding/<str:uidb64>/<str:token>/', views.verify_on_boarding_token,
         name='verify_on_boarding'),
    path('employee/verify_on_boarding/<str:uidb64>/<str:token>/check/username/', views.check_username,
         name='checkUsername'),
    path('employee/on_boarding/', views.on_boarding_new_employee, name='on_boarding_employee'),
    path('employee/on_boarding/<int:user_id>/resend/', views.resend_on_boarding_link, name='on_boarding_resend_link'),
    path('employee/profile/<int:pk>/', views.view_my_profile, name='myprofile_detail'),
    path('employee/profile/<int:userID>/edit/', views.get_user_profile_form, name='user_profile_form'),
    path('employee/personalinfo/<int:userID>/edit/', views.get_user_personal_info_form, name='user_personalinfo_form'),
    path('employee/bankinfo/<int:userID>/edit/', views.get_user_bank_info_form, name='user_bankinfo_form'),
    path('employee/emergencycontact/<int:userID>/edit/', views.get_user_emergency_contact_form,
         name='user_emergencycontact_form'),
    path('employee/educationinfo/<int:userID>/edit/', views.get_user_education_info_form,
         name='user_educationinfo_form'),
    path('employee/experience/<int:userID>/edit/', views.get_user_experience_form, name='user_experience_form'),
    path('employee/document/<int:userID>/edit/', views.get_user_documents_form, name='user_document_form'),
    # path('company_profile/<int:pk>/', views.CompanyProfileDetailView.as_view(), name='mycompany_detail'),
    path('company_profile/<int:pk>/edit/', views.CompanyProfileUpdateView.as_view(), name='mycompany_edit'),
    path('departments/', views.company_departments, name='showDepartments'),
    path('department/new/', views.create_n_edit_department, name='createDepartment'),
    path('department/<int:dep_id>/edit/', views.create_n_edit_department, name='editDepartment'),
    path('department/<int:dep_id>/delete/', views.delete_department, name='deleteDepartment'),
    path('designations/', views.department_designations, name='showDesignations'),
    path('designation/new/', views.create_n_edit_designation, name='createDesignation'),
    path('designation/<int:design_id>/edit/', views.create_n_edit_designation, name='editDesignation'),
    path('designation/<int:dep_id>/get/', views.get_designation, name='getDesignation'),
    path('designation/<int:design_id>/delete/', views.delete_designation, name='deleteDesignation'),
    path('stakeholder/', views.view_company_clients, name='view_clients'),
    path('stakeholder/new/', views.create_company_client, name='new_client'),
    path('stakeholder/profile/<int:client_id>/', views.view_client_profile, name='clientprofile_detail'),
    path('stakeholder/profile/<int:client_id>/edit', views.get_client_edit_form, name='clientprofile_edit'),
    path('employee/salary_edit/<int:user_id>/<int:salary_id>/', views.edit_salary_form, name='edit_salary_form'),
    path('announcements/', views.AnnouncementView.as_view(), name='announcements'),
    path('delete_announcement_list/<int:pk>/', views.delete_announcement_list, name='delete_announcement_list'),
    path('activation_status/<int:pk>/', views.activateion_status, name='activation_status'),
    path('localization/', views.localization, name='localization'),
    path('color_picker/', views.color_picker, name='color_picker'),
    path('select-timezone/', views.change_timezone, name='change_timezone'),
]
