# Generated by Django 3.0.2 on 2023-01-09 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models
import home.validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20230109_0843'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileDirectoryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fileDirectoryType', to='accounts.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('serial_number', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Assigned', 'Assigned'), ('Damaged', 'Damaged'), ('Deployed', 'Deployed'), ('Stocked', 'Stocked')], default='Stocked', max_length=10, null=True, verbose_name='Status Of Leave request')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_assigned', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='accounts.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('file', models.FileField(max_length=1000, upload_to=home.models.get_company_file_path, validators=[home.validator.MaxSizeValidator(5)], verbose_name='File')),
                ('type', models.CharField(blank=True, max_length=200, null=True, verbose_name='File Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userFileCompany', to='accounts.Company', verbose_name='Company')),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fileTypeCompanyFiles', to='home.FileDirectoryType', verbose_name='File Directory')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='userSharedFiles', to=settings.AUTH_USER_MODEL, verbose_name='Shared With')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userCompanyFiles', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=home.models.get_company_bookmarks_path, validators=[home.validator.MaxSizeValidator(5)], verbose_name='Icon')),
                ('marked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='accounts.Company')),
            ],
        ),
    ]
