# Generated by Django 3.0.2 on 2023-01-09 08:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('priority', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('file', models.FileField(blank=True, max_length=1000, null=True, upload_to='task_files/')),
                ('due_date', models.DateTimeField(verbose_name='Due Date')),
                ('status', models.CharField(blank=True, choices=[('start', 'Start'), ('finished', 'Finished'), ('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='start', max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
