# Generated by Django 3.0.2 on 2023-01-09 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payroll.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Amount')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=10, verbose_name='Status Of Claim')),
                ('active', models.BooleanField(default=False)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date From')),
                ('end_date', models.DateField(verbose_name='Date To')),
                ('gross_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('net_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('amount_401K', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('overtime', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overtime_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('working_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('leave_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('payroll_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Payroll Code')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_payroll', to='accounts.Company', verbose_name='Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payroll', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Payroll Policy Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('pay_period_start', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th'), (11, '11th'), (12, '12th'), (13, '13th'), (14, '14th'), (15, '15th'), (16, '16th'), (17, '17th'), (18, '18th'), (19, '19th'), (20, '20th'), (21, '21th'), (22, '22th'), (23, '23th'), (24, '24th'), (25, '25th'), (26, '26th'), (27, '27th'), (28, '28th'), (29, '29th'), (30, '30th'), (31, '31th'), (32, 'LastDay')])),
                ('pay_period_end', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th'), (9, '9th'), (10, '10th'), (11, '11th'), (12, '12th'), (13, '13th'), (14, '14th'), (15, '15th'), (16, '16th'), (17, '17th'), (18, '18th'), (19, '19th'), (20, '20th'), (21, '21th'), (22, '22th'), (23, '23th'), (24, '24th'), (25, '25th'), (26, '26th'), (27, '27th'), (28, '28th'), (29, '29th'), (30, '30th'), (31, '31th'), (32, 'LastDay')])),
                ('pay_period_start_date', models.DateField(verbose_name='Pay Period Start Date')),
                ('pay_period_end_date', models.DateField(verbose_name='Pay Period End Date')),
                ('next_pay_period_start_date', models.DateField()),
                ('next_pay_period_end_date', models.DateField()),
                ('payroll_cycle', models.CharField(choices=[('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('bi_monthly', 'Bi-Monthly')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='accounts.Company', verbose_name='Company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL, verbose_name='Attendance Policy Created By')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryAdjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('adjustment_type', models.CharField(blank=True, choices=[('benefit', 'Benefit'), ('deduction', 'Deduction'), ('claim', 'Claim')], max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_salary_adjustments', to='accounts.Company')),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_salary_adjustments', to='payroll.Payroll')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_salary_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PendingPayrolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('working_hours_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('benefit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('deduction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True)),
                ('taxes_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overtime', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('working_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('leave_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_pending_payrolls', to='accounts.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pending_payrolls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollTaxItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Payroll Item Name')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tax Percentage')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrollTaxItemCompany', to='accounts.Company', verbose_name='Company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_tax_item_user', to=settings.AUTH_USER_MODEL)),
                ('payroll_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_tax_item_policy', to='payroll.PayrollPolicy', verbose_name='Payroll Policy Name')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Payroll Item Name')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tax Percentage')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_payroll_taxes', to='accounts.Company')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_taxes', to='payroll.Payroll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payroll_tax', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Payroll Item Name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=40, verbose_name='Amount')),
                ('adjustment_type', models.CharField(blank=True, choices=[('benefit', 'Benefit'), ('deduction', 'Deduction'), ('OverTime', 'OverTime')], max_length=25, null=True, verbose_name='Item Type')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrollItemCompany', to='accounts.Company', verbose_name='Company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_item_user', to=settings.AUTH_USER_MODEL)),
                ('payroll_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_item_policy', to='payroll.PayrollPolicy', verbose_name='Payroll Policy Name')),
            ],
        ),
        migrations.CreateModel(
            name='HealthInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('company_amount', models.DecimalField(decimal_places=2, default=0, max_digits=40)),
                ('employee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=40)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_health_insurances', to='accounts.Company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_insurance_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_types', to='accounts.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=1000, null=True, upload_to=payroll.models.get_company_claims_path, verbose_name='File')),
                ('type', models.CharField(blank=True, max_length=25, null=True, verbose_name='File Type')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_images', to='payroll.Claim')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_images_company', to='accounts.Company')),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='payroll.ClaimType'),
        ),
        migrations.AddField(
            model_name='claim',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_claims', to='accounts.Company'),
        ),
        migrations.AddField(
            model_name='claim',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_claims', to=settings.AUTH_USER_MODEL),
        ),
    ]
