# Generated by Django 3.0.2 on 2023-01-09 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('tasks', '0001_initial'),
        ('accounts', '0002_auto_20230109_0843'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTaskName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Manual_task_name', to='accounts.Company')),
            ],
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('status', models.CharField(blank=True, choices=[('REJECTED', 'REJECTED'), ('APPROVED', 'APPROVED'), ('PENDING', 'PENDING')], default='PENDING', max_length=25, null=True)),
                ('submit_status', models.CharField(blank=True, choices=[('SAVED', 'SAVED'), ('SUBMITTED', 'SUBMITTED')], default='SAVED', max_length=25, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyTimeLog', to='accounts.Company')),
                ('manual_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='timelog.ManualTaskName')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectTimeLog', to='project.Project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskTimeLog', to='tasks.Card')),
            ],
        ),
    ]
