# Generated by Django 3.0.2 on 2023-01-09 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Attendance Date')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('total_break', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total Break')),
                ('total_duration', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total Duration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Attendance Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Attendance Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeAttendanceCompany', to='accounts.Company', verbose_name='Company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeAttendance', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Shift Name')),
                ('start_time', models.TimeField(verbose_name='Shift Start Time')),
                ('end_time', models.TimeField(verbose_name='Shift End Time')),
                ('weekdays', multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100, verbose_name='Weekend Days')),
                ('shift_Allowance', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Shift Allowance Amount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiftCompany', to='accounts.Company', verbose_name='Company Name')),
            ],
        ),
        migrations.CreateModel(
            name='AttendancePunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.TimeField(verbose_name='Punch In Time')),
                ('out_time', models.TimeField(blank=True, null=True, verbose_name='Punch Out Time')),
                ('duration', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='Punch duration')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendancePunch', to='attendance.Attendance', verbose_name='Attendance')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendancePunchCompany', to='accounts.Company', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Attendance Policy Name')),
                ('description', models.TextField(verbose_name='Attendance Policy Description')),
                ('grace_time', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Grace Time')),
                ('overtime', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Overtime Allowed')),
                ('working_hour_policy', models.CharField(choices=[('Normal', 'First Check-in & Last Check-out'), ('Strict', 'Every Valid Check-in & Check-out ')], max_length=50, verbose_name='Working Hour Policy')),
                ('working_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total Working Hour Time Allowed')),
                ('policy_status', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendancePolicyCompany', to='accounts.Company', verbose_name='Company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendancePoilcyCreator', to=settings.AUTH_USER_MODEL, verbose_name='Attendance Policy Created By')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendanceShift', to='attendance.Shift', verbose_name='Shift')),
            ],
        ),
    ]
